### PR TITLE
Update higan-099.ebuild

### PR DESCRIPTION
**Pull request by bradleyaswain**
Add p7zip dependency for unpacking the .7z file

### CODE REVIEW

**Comment by apinsard** [comment]
Hi @bradleyaswain, we cannot merge pull requests directly on this repo (see https://github.com/funtoo/ports-2012#greetings-github-users).

Please file a new issue at https://bugs.funtoo.org/ to describe the issue an suggest your fix. Moreover, `games-emulation/higan` is not forget in Funtoo, so we would need to ask Gentoo to make the changes in the first place.

**Comment by antematherian** [comment]
@bradleyaswain thank you for pointing out the problem with the ebuild! The correct place to open pull requests in most cases is: https://github.com/funtoo/funtoo-overlay 
And you should open a similar pull request on bugs.funtoo.org so we can better keep track of changes to the portage tree.

If you want to skip the bureaucracy, you can ping me  on irc.freenode.net at #funtoo 
or preferably send me an email at hencb@vorangerie.com, and I'll open the corresponding 
bug and pull requests at the right place, or contact the maintainers who might be interested in fixing the bug. 

@apinsard The source file for the distfiles is a .7z file. You cannot install the package without p7zip. The version bump from higan-094 to higan-099 changed the format of the source files from tar.gz. to .7z, so p7zip is an essential dependency. This should be fixed asap, according to "Does it build?" from http://www.funtoo.org/Funtoo_Linux_Vision

I'll contact the gentoo maintainers.

**Comment by antematherian** [comment]
Opened an equivalent issue on our bugtracker. https://bugs.funtoo.org/browse/FL-3500

In cases like these, if upstream doesn't fix the issue, we have to fork.

The procedure looks similar to this:
fork the funtoo-overlay repository through github https://github.com/funtoo/funtoo-overlay
git clone the overlay to your local computer
check that the gentoo portage tree doesn't have a newer version of the ebuild that fixes the issue: 
https://github.com/gentoo/gentoo (in this case, it doesn't https://github.com/gentoo/gentoo/tree/master/games-emulation/higan) 
create the directory in your local overlay for the package: e.g. mkdir -p /var/overlay/funtoo-overlay/games-emulation/higan
copy over the contents of the regular portage tree ebuild directory to the overlay:
cp -r /usr/portage/games-emulation/higan/* /var/overlay/funtoo-overlay/games-emulation/higan

In this case, you should probably copy over the ebuild to a newer version and name it:
higan-099-r1.ebuild, and add the line you suggested to the ebuild. For more info on the naming convention, check https://devmanual.gentoo.org/ebuild-writing/file-format/

if you added a new source file (not in this case) regenerate the manifest file (in the /var/overlay/funtoo-overlay/games-emulation/higan directory):
using app-portage/repoman: repoman manifest
using the ebuild command: ebuild higan-099-r1.ebuild manifest
The manifest contains checksums for the source file. Since we haven't changed the SRC_URI line in the ebuild, you don't need to use this command.

when you're finished, commit your changes and open a pull request on funtoo-overlay.
Don't worry: we'll try to fix any discrepancies that might arise in the process. 

Opening a pull request and bug report allows more developers to see your changes and gives an easier overview of the changes that were made to the portage tree. It might be more work upfront,
but it allows an easier overview of what ebuilds were forked at what time, and what changes were made.

Good luck, and thanks for helping us make a better Funtoo!

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/FL-3501

**Comment by danielrobbins** [comment]
This issue has been resolved in the Funtoo Linux bug tracker. Closing on GitHub.

**Pull request closed without merging**
